title: Christopher B. Johnson's Portfolio
logo: /assets/img/logo.png
description: Data Geek | Data Analysis | Data Engineering | Python | Always Asking Why
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

